# fly.toml app configuration file generated for server-glowing-bird-431 on 2026-05-31T20:33:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-glowing-bird-431'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
